source 'https://rubygems.org'

gem 'xcpretty'
gem 'i18n'
gem 'fui'
gem 'obcd'
gem 'cocoapods'
gem 'shenzhen'
gem 'deliver'
gem 'codes'
gem 'rake'
gem 'cocoapods-keys'
gem 'pygmentize'
gem 'did_you_mean', '~> 1.4.0'
gem 'etc', '~> 1.1.0'
gem 'fileutils', '~> 1.4.1'
gem 'delegate', '~> 0.1.0'
gem 'uri', '~> 0.10.0'
gem 'strscan', '~> 1.0.3'
gem 'timeout', '~> 0.1.0'
gem 'zlib', '~> 1.1.0'
gem 'stringio', '~> 0.1.0'
