source 'https://github.com/splinesoft/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

project 'Mudrammer'

deployment_target = '11.0'
inhibit_all_warnings!

plugin 'cocoapods-keys', {
  :project => "Mudrammer",
  :keys => [
    "SPLINESOFT_AFFILIATE_KEY",
  ]
}

target 'MUDRammer' do

  # Splinesoft
  pod 'BlocksKit', :git => 'https://github.com/zac/BlocksKit.git', :branch => 'xcode-14.3.1-fixes'
  pod 'SPLCore', :git => 'https://github.com/zac/SPLCore.git', :branch => 'xcode-14.3.1-fixes'
  pod 'SSAccessibility', '0.2.0'
  pod 'SSDataSources', '0.8.6'
  pod 'SSOperations', '0.1.0'
  pod 'SSApplication', '0.3.0'

  # Networking
  pod 'CocoaAsyncSocket', '7.3.5'
  pod 'libtelnet', '0.21' # via SPLSpecs

  # Engine
  pod 'SAMRateLimit', '0.2.0'
  pod 'KVOController', '1.0.3'
  pod 'OSCache', '1.2'
  pod 'MyLilTimer', '0.1.0'

  # UI
  pod 'DAKeyboardControl', '2.4.0'
  pod 'TTTAttributedLabel', '1.13.1'
  pod 'JASidePanels', '1.3.2'
  pod 'Masonry', '0.6.2'
  pod 'JSQSystemSoundPlayer', '4.0.0'
  pod 'JTSImageViewController', '1.4'
  pod 'IFTTTLaunchImage', '0.4.1'

  # Forms
  pod 'QuickDialog', :subspecs => ['Core', 'Extras'], :git => 'https://github.com/zac/QuickDialog.git', :branch => 'xcode-14.3.1-fixes'
  pod 'FXForms', '1.2.13'

  # Pods Ack.
  pod 'VTAcknowledgementsViewController', '0.14'

  target 'MRTests' do
    inherit! :search_paths
    pod 'Expecta'
    pod 'OCMock'
  end
end

# `pod install` resets all pod deployment targets after each install.
# Ensure that MUDRammer builds with 8.0 but supports a minimum deploy target of 7.0.
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |pod_target|
        pod_target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end

